/*****************************************************************************
 * Project: RooFit                                                           *
 *                                                                           *
  * This code was autogenerated by RooClassFactory                            * 
 *****************************************************************************/

#ifndef ROORELBWPS2
#define ROORELBWPS2

#include "RooAbsPdf.h"
#include "RooRealProxy.h"
#include "RooCategoryProxy.h"
#include "RooAbsReal.h"
#include "RooAbsCategory.h"
 
class RooRelBWPS2 : public RooAbsPdf {
public:
  RooRelBWPS2() {} ; 
  RooRelBWPS2(const char *name, const char *title,
	      RooAbsReal& _x,
	      RooAbsReal& _pt,
	      RooAbsReal& _mass,
	      RooAbsReal& _width);
  RooRelBWPS2(const RooRelBWPS2& other, const char* name=0) ;
  virtual TObject* clone(const char* newname) const { return new RooRelBWPS2(*this,newname); }
  inline virtual ~RooRelBWPS2() { }

protected:

  RooRealProxy x ;
  RooRealProxy pt ;
  RooRealProxy mass ;
  RooRealProxy width ;
  
  Double_t evaluate() const ;

private:

  ClassDef(RooRelBWPS2,1) // Your description goes here...
};
 
#endif
